apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-web-server
  template:
    metadata:
      labels:
        app: java-web-server
    spec:
      containers:
        - name: java-web-server
          image: sergeizh/java-web-server:${COMMIT_HASH}
          ports:
            - containerPort: 8080
