name: Build and Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PW }}

      # Build Docker image
      - name: Build Docker Image
        run: cd app && docker build -t java-web-server .

      - name: Tag image
        run: docker tag java-web-server sergeizh/java-web-server:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push sergeizh/java-web-server:latest

      # Trigger ArgoCD to sync the app
      - name: Trigger ArgoCD Sync
        run: |
          curl -X POST http://a09ab25cff03d410195244b334e4b653-7f5a5ff112fff0c0.elb.us-east-1.amazonaws.com/api/webhook \
            -H "Content-Type: application/json" \
            -d '{
                  "name": "java-web-server-app",
                  "namespace": "argocd"
                }'
